language: ruby
cache: bundler

rvm:
  - 2.6

install:
  - bundle install

script:
  - bundle exec jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  repo: mskian/status-blog
  token: $GITHUB_TOKEN
  keep_history: true
  fqdn: vijaygopalbalasa.github.io
  on:
    branch: master
