title: San Status
logo: /assets/icons/Icon-72.png
description: Vijaygopal Balasa - Status and Text notes.
lang: en
timezone: Asia/Kolkata
author:
  name: "Vijaygopal Balasa"
  twitter: "Vijaygopalbala1"
  email: "vijaygopal@androidstrike.com"
  url: "https://vijaygopalbalasa.github.io/"

baseurl:
url: https:///status.vijaygopal.github.io

email: vijaygopal@androidstrike.com

markdown: kramdown
highlighter: none
kramdown:
   syntax_highlighter_opts:
      disable : true

source: .
destination: ./_site
permalink: /:title/
paginate: 3
paginate_path: /page/:num/

compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

twitter:
  username: vijaygopalbala1
  card: summary

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      image: /assets/san-status-thumb.jpg

jekyll_compose:
  default_front_matter:
    posts:
      description:
      permalink:
      author:
      image:

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
- README.md
- Gemfile
- Gemfile.lock
- .sass-cache
- LICENSE.md
- .bundle
- .asset-cache

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-compose
